#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# Copyright (c) 2021 inett GmbH
# License: GNU General Public License v2
# A file is subject to the terms and conditions defined in the file LICENSE,
# which is part of this source code package.
import datetime
import json
import re
from concurrent.futures import ThreadPoolExecutor
import logging
import sys
import urllib.parse
from contextlib import contextmanager
from json import JSONDecodeError
from typing import Mapping, Any, Sequence, Iterable, Callable, Generator

import requests
import requests.adapters
import urllib3
from pathlib import Path

from cmk.utils import password_store
from cmk.special_agents.v0_unstable.argument_parsing import Args, create_default_argument_parser
from cmk.special_agents.v0_unstable.agent_common import (
    CannotRecover,
    special_agent_main,
)
from cmk.utils.paths import tmp_dir

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

AGENT = "proxmox_bs"
CacheFilePath = tmp_dir / "special_agents" / f"agent_{AGENT}" / "agent_cache.json"
LOGGER = logging.getLogger(f"agent_{AGENT}")

RequestStructure = Sequence[Mapping[str, Any]] | Mapping[str, Any]

Datastore_Structure = {
    "gc": {},
    "groups": [],
    "namespace": [],
    "snapshots": [],
    "status": {},
}
NamespaceStructure = {
    "groups": [],
    "snapshots": [],
}


class ProxmoxBsSession:
    """Session"""

    class HTTPAuth(requests.auth.AuthBase):
        """Auth"""

        def __init__(
            self,
            base_url: str,
            credentials: Mapping[str, str],
            timeout: int,
            verify_ssl: bool,
        ) -> None:
            super().__init__()
            ticket_url = base_url + "api2/json/access/ticket"
            response = (
                requests.post(url=ticket_url, verify=verify_ssl, data=credentials, timeout=timeout)
                .json()
                .get("data")
            )

            if response is None:
                raise CannotRecover(
                    "Couldn't authenticate {!r} @ {!r}".format(
                        credentials.get("username", "no-username"), ticket_url
                    )
                )

            self.pbs_auth_cookie = response["ticket"]
            self.csrf_prevention_token = response["CSRFPreventionToken"]

        def __call__(self, r: requests.PreparedRequest) -> requests.PreparedRequest:
            r.headers["CSRFPreventionToken"] = self.csrf_prevention_token
            return r

    def __init__(
            self,
            endpoint: tuple[str, int],
            credentials: Mapping[str, str],
            verify_ssl: bool,
            timeout: int,
            token_auth: bool
    ) -> None:
        def create_session():
            session = requests.Session()
            adapter = requests.adapters.HTTPAdapter(pool_maxsize=100)
            session.mount('https://', adapter)
            if token_auth:
                session.headers['Authorization'] = f"PBSAPIToken={credentials['username']}:{credentials['password']}"
            else:
                session.auth = self.HTTPAuth(self._base_url, credentials, timeout, verify_ssl)
                session.cookies = requests.cookies.cookiejar_from_dict(
                    {"PBSAuthCookie": session.auth.pbs_auth_cookie}
                )
            session.headers["Connection"] = "keep-alive"
            session.headers["accept"] = ", ".join(
                (
                    "application/json",
                    "application/x-javascript",
                    "text/javascript",
                    "text/x-javascript",
                    "text/x-json",
                )
            )
            return session

        self._timeout = timeout
        self._verify_ssl = verify_ssl
        self._base_url = "https://%s:%d/" % endpoint
        self._session = create_session()

    def __enter__(self) -> Any:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    def close(self) -> None:
        """close connection to Proxmox BS endpoint"""
        self._session.close()

    def get_api_element(self, base_path: str, path: str, options=None) -> object:
        """do an API GET request"""
        option_string = ""
        if isinstance(options, Mapping):
            if options is not None:
                first = True
                for key, value in options.items():
                    if isinstance(key, str) and isinstance(value, str):
                        if not first:
                            option_string += "&"
                        else:
                            option_string += "?"
                            first = False
                        option_string += f"{urllib.parse.quote_plus(key)}={urllib.parse.quote_plus(value)}"

        try:
            return self._get_raw(base_path + path + option_string)
        except requests.exceptions.ReadTimeout:
            raise CannotRecover(f"Read timeout after {self._timeout}s when trying to GET {path}")
        except requests.exceptions.ConnectionError as exc:
            raise CannotRecover(f"Could not GET element {path} ({exc})") from exc
        except JSONDecodeError as e:
            raise CannotRecover("Couldn't parse API element %r" % path) from e

    def _get_raw(self, sub_url: str) -> object:
        return (
            self._get_logs_or_tasks_paginated(sub_url)
            if (sub_url.endswith("/log") or sub_url.endswith("/tasks"))
            else self._validate_response(
                self._session.get(
                    url=self._base_url + sub_url,
                    verify=self._verify_ssl,
                    timeout=self._timeout,
                ),
                sub_url,
            )
        )

    def _get_logs_or_tasks_paginated(self, sub_url: str) -> list[object]:
        url = self._base_url + sub_url
        data: list[object] = []
        start = 0
        page_size = 5000

        while True:
            response_data = self._validate_response(
                self._session.get(
                    url=url,
                    verify=self._verify_ssl,
                    timeout=self._timeout,
                    params={"start": start, "limit": page_size},
                ),
                sub_url,
            )
            assert isinstance(response_data, Sequence)
            data += response_data

            if len(response_data) < page_size:
                break

            start += page_size

        return data

    @staticmethod
    def _validate_response(response: requests.Response, sub_url: str) -> object:
        if not response.ok:
            return []
        response_json = response.json()
        if "errors" in response_json:
            raise CannotRecover(
                "Could not fetch {!r} ({!r})".format(sub_url, response_json["errors"])
            )
        return response_json.get("data")


class ProxmoxBsAPI:
    """Wrapper for ProxmoxPbSession which provides high level API calls"""
    def __init__(
        self, host: str, port: int, credentials: Any, timeout: int, verify_ssl: bool, token_auth: bool
    ) -> None:
        try:
            LOGGER.info("Establish connection to Proxmox BS host %r", host)
            self._session = ProxmoxBsSession(
                endpoint=(host, port),
                credentials=credentials,
                timeout=timeout,
                verify_ssl=verify_ssl,
                token_auth=token_auth,
            )
        except requests.exceptions.ConnectTimeout:
            raise CannotRecover(f"Timeout after {timeout}s when trying to connect to {host}:{port}")
        except requests.exceptions.ConnectionError as exc:
            raise CannotRecover(f"Could not connect to {host}:{port} ({exc})") from exc

    def __enter__(self) -> Any:
        self._session.__enter__()
        return self

    def __exit__(self, *exc_info: object) -> None:
        self._session.__exit__(*exc_info)
        self._session.close()

    def get(self, base_path: str, path: str | Iterable[str], options=None) -> Any:
        """Handle request items in form of 'path/to/item' or ['path', 'to', 'item']"""
        return self._session.get_api_element(
            base_path,
            path if isinstance(path, str) else "/".join(map(str, path)),
            options=options
        )

    def get_tree(self, requested_structure: RequestStructure, base_path="api2/json/", options=None) -> Any:
        def rec_get_tree(
            element_name: str | None,
            requested_structure: RequestStructure,
            base_path: str,
            path: Iterable[str],
            options=None,
        ) -> Any:
            """Recursively fetch data from API to match <requested_structure>"""

            def is_list_of_subtree_names(data: RequestStructure) -> bool:
                """Return True if given data is a list of dicts containing names of subtrees,
                e.g [{'name': 'log'}, {'name': 'options'}, ...]"""
                return bool(data) and all(
                    isinstance(elem, Mapping) and tuple(elem) in {("name",), ("subdir",), ("cmd",), ("store",)}
                    for elem in data
                )

            def extract_request_subtree(request_tree: RequestStructure) -> RequestStructure:
                """If list if given return first (and only) element return the provided data tree"""
                return (
                    request_tree
                    if isinstance(request_tree, Mapping)
                    else next(iter(request_tree))
                    if len(request_tree) > 0
                    else {}
                )

            def extract_variable(st: RequestStructure) -> Mapping[str, Any] | None:
                """Check if there is exactly one root element with a variable name,
                e.g. '{node}' and return its stripped name"""
                if not isinstance(st, Mapping):
                    return None
                if len(st) != 1 or not next(iter(st)).startswith("{"):
                    # we have either exactly one variable or no variables at all
                    assert len(st) != 1 or all(not e.startswith("{") for e in st)
                    return None
                key, value = next(iter(st.items()))
                assert len(st) == 1 and key.startswith("{")
                return {"name": key.strip("{}"), "subtree": value}

            next_path = list(path) + ([] if element_name is None else [element_name])
            subtree = extract_request_subtree(requested_structure)
            variable = extract_variable(subtree)
            response = self._session.get_api_element(base_path, "/".join(map(str, next_path)), options=options)

            if isinstance(response, Sequence):
                # Handle subtree stubs like [{'name': 'log'}, {'name': 'options'}, ...]
                if is_list_of_subtree_names(response):
                    assert variable is None
                    assert not isinstance(requested_structure, Sequence) and isinstance(
                        subtree, Mapping
                    )
                    assert subtree
                    subdir_names = (
                        (
                            elem[
                                next(
                                    identifier
                                    for identifier in ("name", "subdir", "cmd")
                                    if identifier in elem
                                )
                            ]
                        )
                        for elem in response
                    )
                    return {
                        key: rec_get_tree(key, subtree[key], base_path, next_path, options=options)
                        for key in subdir_names
                        if key in subtree
                    }

                # Handle case when response is a list of arbitrary datasets
                #  e.g [{'uptime': 12345}, 'id': 'server-1', ...}, ...]"""
                if all(isinstance(elem, Mapping) for elem in response):
                    if variable is None:
                        assert isinstance(subtree, Mapping)
                        return (
                            {key: rec_get_tree(key, subtree[key], base_path, next_path, options=options) for key in subtree}
                            if isinstance(requested_structure, Mapping)
                            else response
                        )  #

                    assert isinstance(requested_structure, Sequence)
                    return [
                        {
                            **elem,
                            **(
                                rec_get_tree(
                                    elem[variable["name"]],
                                    variable["subtree"],
                                    base_path,
                                    next_path,
                                    options=options
                                )
                                or {}
                            ),
                        }
                        for elem in response
                    ]

            return response

        return rec_get_tree(None, requested_structure, base_path, [], options=options)

    def get_datastore(self, datastore: str, datastore_structure: Mapping[str, Any], namespace_structure=None) -> Mapping[str, Any] | None:
        """Read Data from all datastores, as well as their namespaces"""
        data = self.get_tree(
            datastore_structure,
            f"api2/json/admin/datastore/{datastore}/",
        )
        data['store'] = datastore
        if datastore_structure.__contains__('namespace') and namespace_structure is not None:
            data['namespace'] = [self.get_namespace(datastore, ns['ns'], namespace_structure) for ns in data['namespace'] if ns['ns'] != ""]

        return data

    def get_namespace(self, datastore: str, namespace: str, namespace_structure: Mapping[str, Any]) -> Mapping[str, Any] | None:
        data = self.get_tree(
            namespace_structure,
            f"api2/json/admin/datastore/{datastore}/",
            options={
                "ns": namespace,
            }
        )
        data['name'] = namespace

        return data


@contextmanager
def JsonCachedData(path: Path):
    path.parents[0].mkdir(parents=True, exist_ok=True)
    try:
        with path.open(mode="r") as cache_file:
            cache = json.load(cache_file)
        LOGGER.debug("Cache: loaded present cache")
    except (FileNotFoundError, json.JSONDecodeError):
        LOGGER.warning("Cache: could not find file - start a new one")
        cache = {'cache_time': 0.0}

    try:
        yield cache
    finally:
        with path.open(mode="w+") as cache_file:
            json.dump(cache, cache_file, indent=2)


def agent_proxmox_bs_main(args: Args) -> int:
    # Read cache file
    with JsonCachedData(CacheFilePath) as cache:
        cache_age = datetime.datetime.now().timestamp() - cache['cache_time']

        if cache_age > args.cache_time:
            pw_id, pw_path = args.password.split(":")
            password = password_store.lookup(Path(pw_path), pw_id)

            with ProxmoxBsAPI(
                host=args.hostname,
                port=args.port,
                credentials={
                    "username": args.username,
                    "password": password,
                },
                timeout=args.timeout,
                verify_ssl=not args.no_cert_check,
                token_auth=True if re.match(r".+@.+!.+", getattr(args, "username")) else False,
            ) as session:
                LOGGER.info("Fetch pbs information..")
                data = session.get_tree(
                    {
                        "admin": {
                            "datastore": [],
                            "gc": [],
                            "prune": [],
                            "sync": [],
                            "verify": [],
                        },
                        "nodes": [],
                        "version": {},
                        "status": {
                            "datastore-usage": [],
                        },
                        "config": {
                            "datastore": [],
                        }
                    }
                )

                with ThreadPoolExecutor(max_workers=100) as executor:
                    futures = [
                        executor.submit(
                            session.get_datastore,
                            ds['store'],
                            Datastore_Structure,
                            NamespaceStructure
                        ) for ds in data['admin']['datastore']
                    ]
                    data['admin']['datastore'] = [v.result() for v in futures if v is not None]

            cache['cache_time'] = datetime.datetime.now().timestamp()
            cache['data'] = data

        else:
            data = cache['data']

        LOGGER.info("Write agent output..")
        sys.stdout.write(f"<<<proxmox_bs:sep(0)>>>\n")

        # Sync Job Section
        if len(data['admin']['sync']) > 0:
            sys.stdout.write(f">sync-jobs<\n")
            for sync_job in data['admin']['sync']:
                sync_job = {
                    key: sync_job.get(key, None) for key in ['id', 'last-run-state', 'last-run-endtime', 'remote']
                }
                sys.stdout.write(f"{json.dumps(sync_job)}\n")

        # Datastore Section
        if len(data['admin']['datastore']) > 0:
            datastore_conf = {}
            for ds in data['config']['datastore']:
                datastore_conf[ds['name']] = {
                    'path': ds['path'],
                    'maintenance-mode': ds.get('maintenance-mode', None),
                }


            sys.stdout.write(f">data-stores<\n")
            for ds in data['admin']['datastore']:
                datastore = {
                    'store': ds['store'],
                    'gc': {
                        'last-run-state': ds['gc'].get('last-run-state', None),
                        'last-run-endtime': ds['gc'].get('last-run-endtime', None),
                        'upid': ds['gc'].get('upid', None),
                    },
                    'groups': _create_group_mapping(ds['groups']),
                    'verification': _create_verification_mapping(ds['snapshots']),
                    'status': ds['status'],
                    'path': datastore_conf[ds['store']]['path'],
                    'maintenance-mode': datastore_conf[ds['store']]['maintenance-mode'],
                    'namespace': []
                }

                for ns in ds['namespace']:
                    datastore['namespace'].append({
                        'namespace': ns['name'],
                        'groups': _create_group_mapping(ns['groups']),
                        'verification': _create_verification_mapping(ns['snapshots']),
                    })

                sys.stdout.write(f"{json.dumps(datastore)}\n")

        # Task Section; This is not cached
        running_tasks = session.get("api2/json/", f"nodes/0/tasks/", options={'running': True, 'limit': 0})
        running_tasks = [{
            'start-time': x['starttime'],
            'worker-type': x['worker_type'],
            'worker-id': x['worker_id']
        } for x in running_tasks]

        if len(running_tasks) > 0:
            sys.stdout.write(f">running-tasks<\n")
            sys.stdout.write(f"{json.dumps(running_tasks)}\n")

    return 0


def _create_group_mapping(groups: list) -> list:
    result = []
    for group in groups:
        result.append({
            'backup-id': group['backup-id'],
            'backup-count': group['backup-count'],
            'last-backup': group['last-backup'],
        })

    return result


def _create_verification_mapping(snapshots: list) -> Mapping[str, Any]:
    result = {
        'ok': 0,
        'fail': 0,
        'fail_list': [],
        'not_verified': 0,
        'unknown_state': 0,
        'unknown_state_list': []
    }
    for snapshot in snapshots:
        verification = snapshot.get('verification', {'state': None})
        match verification['state']:
            case "ok":
                result['ok'] += 1
            case "failed":
                result['fail'] += 1
                result['fail_list'].append({
                    'backup-id': snapshot['backup-id'],
                    'verification-upid': snapshot['verification']['upid'],
                    'verification-state': snapshot['verification']['state'],
                    'backup-time': snapshot['backup-time'],
                })
            case None:
                result['not_verified'] += 1
            case _:
                result['unknown_state'] += 1
                result['unknown_state_list'].append({
                    'backup-id': snapshot['backup-id'],
                    'verification-upid': snapshot['verification']['upid'],
                    'verification-state': snapshot['verification']['state'],
                    'backup-time': snapshot['backup-time'],
                })

    return result


def parse_arguments(argv: Sequence[str] | None) -> Args:
    parser = create_default_argument_parser(description=__doc__)

    parser.add_argument(
        "--username", "-u",
        dest="username",
        required=True,
        help="PBS Username",
    )

    parser.add_argument(
        "--password", "-p",
        dest="password",
        required=True,
        help="PBS Password or API Token",
    )

    parser.add_argument(
        "--port", "-P",
        dest="port",
        type=int,
        default=8007,
        help="PBS Port",
    )

    parser.add_argument(
        "--no-cert-check",
        dest="no_cert_check",
        action="store_true",
        help="If \"True\": Disable TLS certificate check (not recommended!)",
    )

    parser.add_argument(
        "--timeout", "-t",
        type=int,
        default=50,
        help="API call timeout"
    )

    parser.add_argument(
        "--cache-time",
        type=int,
        default=3600,
        help="Cache time for received Data."
    )

    parser.add_argument("hostname",help="PBS Hostname (FQDN or IP)")
    return parser.parse_args(argv)


def main() -> int:
    return special_agent_main(parse_arguments, agent_proxmox_bs_main)


if __name__ == "__main__":
    main()
