#!/bin/bash

inpath() {
    command -v "${1:?No command to test}" >/dev/null 2>&1
}

printf "<<<proxmox_bs>>>\n"

printf "===requirements===\n"
requirement() {
  inpath $1; RC=$?
  printf "$RC $1\n"
}
requirements() {
  RC=0
  while read -r req; do
    line=$( requirement $req )
    trc=$( printf "$line" | cut -d ' ' -f 1 )
    echo $line
    [ "$trc" != "0" ] && RC=1
  done
  return $RC
}
cat <<. | requirements || exit 0
proxmox-backup-manager
proxmox-backup-client
jq
.

command_section() {
  PIPE=
  SECTION_POSTFIX=
  while [[ "$1" == -* ]]; do
    if [ "$1" == "-P" ]; then
      PIPE="${PIPE} | $2"
      shift 2
    fi
    if [ "$1" == "-t" ]; then
      PIPE="${PIPE} | tee $2"
      shift 2
    fi
    if [ "$1" == "-p" ]; then
      SECTION_POSTFIX=$2
      shift 2
    fi
  done
  cmd=$1
  shift
  printf "===$cmd===$SECTION_POSTFIX\n"
  echo sh -c "$cmd $* $PIPE" >&2
  sh -c "$cmd $* $PIPE"
}

$(< /etc/check_mk/proxmox_bs.env)
PBS_REPO="${PBS_USERNAME}@localhost"
proxmox-backup-client login

OUTPUT_FORMAT="--output-format json-pretty"

command_section "proxmox-backup-manager versions" $OUTPUT_FORMAT
TMP_DATASTORES=$( mktemp -p /tmp/ )
command_section -t $TMP_DATASTORES \
  "proxmox-backup-manager datastore list" $OUTPUT_FORMAT

command_section "proxmox-backup-manager task list" $OUTPUT_FORMAT

TMP_UPIDS=$( mktemp -p /tmp/ )

TMP_GC_FILES=$( mktemp -p /tmp/ )
jq -r '.[].name' $TMP_DATASTORES | while read -r name; do
  TMP_GC=$( mktemp -p /tmp/ )
  printf "$TMP_GC" >> "$TMP_GC_FILES"
  command_section -t "$TMP_GC" -p "$name" \
    "proxmox-backup-manager garbage-collection status" $name $OUTPUT_FORMAT
  jq -r '.upid' "$TMP_GC" >> $TMP_UPIDS
  command_section -p "$name" \
    "proxmox-backup-client list" --repository "$PBS_REPO:$name" $OUTPUT_FORMAT
  command_section -p "$name" \
    "proxmox-backup-client snapshot list" --repository "$PBS_REPO:$name" \
    $OUTPUT_FORMAT
  command_section -p "$name" \
    "proxmox-backup-client status" --repository "$PBS_REPO:$name" \
    $OUTPUT_FORMAT
done

cat $TMP_UPIDS | while read -r upid; do
  command_section -P "sed -n '/^Removed garbage: /,\$p'" -p "$upid" \
    "proxmox-backup-manager task log" "$upid"
done

proxmox-backup-client logout --repository "$PBS_REPO"
export PBS_PASSWORD=

printf "$TMP_GC_FILES" >> $TMP_GC_FILES

rm -vf $TMP_DATASTORE $TMP_UPIDS $(cat $TMP_GC_FILES | xargs) >&2

echo "===EOD==="
echo "="

